services:
  postgres_test:
    image: postgres:17.5
    env_file:
      - .env.test
      - .env.test.example
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 7

  app_test:
    build: .
    env_file:
      - .env.test
      - .env.test.example
    command: >
      sh -c "
      uv run alembic upgrade head &&
      uv run pytest -v app/tests/"
    depends_on:
      postgres_test:
        condition: service_healthy
    volumes:
      - .:/app