version: '3.8'

services:
  postgres_test:
    image: postgres:17.5
    env_file:
      - .env.test
      - .env.test.example
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app_test:
    build: .
    env_file:
      - .env.test
      - .env.test.example
    command: bash -c "make install && uv run pytest -v tests/"
    depends_on:
      postgres_test:
        condition: service_healthy