services:
  postgres:
    image: postgres:17.5
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    env_file: .env
    command: uv run alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      migrations:
        condition: service_completed_successfully
    volumes:
      - .:/app

volumes:
  postgres_data: